# Generated by Django 3.0.5 on 2020-11-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-title']},
        ),
    ]
